
import { Ingredient } from './ingredient';
export abstract class Bite {
  // internal flag to know if bite has been processed by recipe
  public init: boolean = false;
  // ingredient generated by cookbook generator, needed by recipe service
  public ingredient: Ingredient;
  // HXL Proxy generated: column name
  public title: string;
  public readonly initialTitle: string;
  // HXL Proxy generated: hxl tag
  public dataTitle: string;

  public displayedDataTitle: string = null;
  // internal to know what type of bite we have inside the template :)
  public type: string;

  public hashCode: number;

  constructor(title: string, type: string) {
    this.title = title.slice(0, 35) + (title.length > 35 ? '...' : '');
    this.initialTitle = this.title;
    this.type = type;
  }

}

