
import { Ingredient } from './ingredient';
export abstract class Bite {

  // internal flag to know if bite has been processed by recipe
  public init: boolean = false;
  // ingredient generated by cookbook generator, needed by recipe service
  public ingredient: Ingredient;
  // HXL Proxy generated: column name
  public title: string;
  public readonly initialTitle: string;
  // HXL Proxy generated: hxl tag
  public dataTitle: string;

  public displayedDataTitle: string = null;
  // internal to know what type of bite we have inside the template :)
  public type: string;

  public hashCode: number;

  // Timeseries or Charts or Key Figures
  public displayCategory;

  public description: string;

  public filteredValues: number[];

  static type(): string {
    return 'bite';
  }

  constructor(title?: string) {
    if (title) {
      this.setTitle(title);
    }
    this.initialTitle = this.title;
    this.type = (this.constructor as typeof Bite).type();

    this.filteredValues = [];
  }

  public setTitle(title: string) {
    this.title = title.slice(0, 55) + (title.length > 35 ? '...' : '');
  }

}

