
import { Ingredient } from './ingredient';
export abstract class Bite {
  // internal flag to know if bite has been processed by recipe
  public init: boolean = false;
  // ingredient generated by cookbook generator, needed by recipe service
  public ingredient: Ingredient;
  // HXL Proxy generated: column name
  public title: string;
  // HXL Proxy generated: hxl tag
  public dataTitle: string;
  // internal to know what type of bite we have inside the template :)
  public type: string;

  constructor(title: string, type: string) {
    this.title = title;
    this.type = type;
  }
}

