version: "2.1"

services:

  quickcharts:
    build: ./quickcharts-dev/
    hostname: quickcharts
    ports:
      - "4201:4202"
    volumes:
    # adapt to point to the app folder on the host
      - "../.:/srv/quickcharts"

    entrypoint: "tail -f /dev/null"
